-- Reglamento II Peña Prieta Skyrace - Camberas APP (3 oct 2026)
-- Volcado del PDF oficial "REGLAMENTO PEÑA PRIETA SKY RACE 2026".
-- Idempotente: si la carrera ya tiene secciones de reglamento, no hace nada.
DO $$
DECLARE
  v_race_id uuid := '4ba602c8-4445-4170-82bf-e37f79b047b3';
  v_reg_id uuid;
BEGIN
  SELECT id INTO v_reg_id FROM race_regulations WHERE race_id = v_race_id LIMIT 1;
  IF v_reg_id IS NULL THEN
    INSERT INTO race_regulations (race_id, published, version)
    VALUES (v_race_id, false, 1)
    RETURNING id INTO v_reg_id;
  END IF;

  IF EXISTS (SELECT 1 FROM race_regulation_sections WHERE regulation_id = v_reg_id) THEN
    RAISE NOTICE 'El reglamento ya tiene secciones; no se inserta nada.';
    RETURN;
  END IF;

  INSERT INTO race_regulation_sections (regulation_id, section_type, title, content, section_order, is_required) VALUES
  (v_reg_id, 'general_info', 'Información General',
E'El Ayuntamiento de Vega de Liébana, en colaboración con la Asociación Cultural Deportiva Torrecerredo, organiza el evento PEÑA PRIETA SKY RACE el día 3 de octubre de 2026, que engloba las siguientes pruebas:\n\n• PEÑA PRIETA SKY RACE: salida y meta en Vega de Liébana (09:00 h). 36 km y 2.600 m de desnivel positivo. Abierta a federados y no federados. Limitada a 300 participantes.\n• PEÑA PRIETA TRAIL: salida y meta en Vega de Liébana (09:30 h). 8 km y 560 m de desnivel positivo. Abierta a federados y no federados; para categorías inferiores y adultos que quieran iniciarse en el trail. Limitada a 100 participantes.\n• PEÑA PRIETA MARCHA: salida y meta en Vega de Liébana (09:30 h). 8 km y 560 m de desnivel positivo. Marcha no competitiva, abierta a federados y no federados. Limitada a 100 participantes.\n\nTiempo máximo de cada prueba:\n• SKY RACE: 8 horas.\n• TRAIL: 4 horas.\n• MARCHA: 4 horas.', 1, true),

  (v_reg_id, 'registration', 'Inscripción',
E'Para participar, el corredor debe tener como mínimo la edad establecida para la categoría más joven permitida en cada competición.\n\nPrecios de inscripción:\n• PEÑA PRIETA SKY RACE: 40 € (no federados 45 €).\n• PEÑA PRIETA TRAIL: 15 € (no federados 20 €).\n• PEÑA PRIETA MARCHA: 10 €.\n\nLa inscripción incluye:\n• El derecho a participar en la prueba.\n• Avituallamientos líquidos y sólidos durante la carrera y en meta.\n• Asistencia durante la carrera mediante el dispositivo de seguridad de la organización.\n• Sistema de cronometraje por chip (SKY RACE y TRAIL).\n• Almuerzo en meta el día 3 de octubre.\n• Servicio de duchas y WC en el centro de competición.\n• Obsequio de material deportivo.\n• Medalla Finisher para quienes finalicen la SKY RACE.\n\nCuando se agoten las plazas disponibles, la organización creará una lista de reserva para asignar los dorsales que vayan quedando libres.', 2, true),

  (v_reg_id, 'bib_collection', 'Recogida de Dorsales, Chips y Control de Material',
E'• Para retirar el dorsal es obligatorio presentar el DNI.\n• Con el dorsal se entregará un chip de cronometraje personal e intransferible.\n• La organización no enviará la bolsa del corredor a quienes no asistan al evento, ni se permitirá su recogida una vez terminado.\n• En caso de abandono, el participante debe avisar inmediatamente a la organización en el punto de control más cercano y devolver el dorsal.\n• El control de material podrá realizarse a petición de los jueces de carrera en el acceso a la zona de salida o en cualquier punto del circuito.', 3, false),

  (v_reg_id, 'refund_policy', 'Cancelaciones y Devoluciones',
E'• Derecho a devolución del 50% de la inscripción antes del 15 de septiembre de 2026, previa solicitud con documento que acredite causa de gravedad o fuerza mayor. Después de ese plazo no se realizarán devoluciones.\n• Las cancelaciones deben solicitarse a través del procedimiento establecido en la plataforma de inscripciones.\n• Se permite el cambio de titularidad del dorsal en casos excepcionales y justificados, siempre antes del 20 de septiembre de 2026.\n• La organización se reserva el derecho de modificar o suspender la carrera por fuerza mayor. Si ocurre al menos 5 días antes de la prueba, o si se interrumpe tras la salida, no habrá reembolso: se guardará el dorsal para el próximo año.', 4, true),

  (v_reg_id, 'classifications', 'Categorías, Trofeos y Premios',
E'Categorías (masculinas y femeninas):\n• Cadete: 15-16 años (solo TRAIL).\n• Juvenil: 17-18 años (solo TRAIL).\n• Júnior: 19-20 años (solo TRAIL).\n• Promesa: 21-23 años (ambas pruebas).\n• Senior: 24-39 años (solo SKY RACE).\n• Absoluta: todos los participantes (ambas pruebas).\n\nSubcategorías (solo SKY RACE):\n• Veterana A: 40-49 años.\n• Veterana B: 50-59 años.\n• Veterana C: a partir de 60 años.\n\nLa edad de referencia para toda la temporada es la del 31 de diciembre del año de la competición.\n\nPremios PEÑA PRIETA SKY RACE:\n• 1º absoluto masc. y fem.: trofeo y 200 €.\n• 2º absoluto masc. y fem.: trofeo y 100 €.\n• 3º absoluto masc. y fem.: trofeo y 50 €.\n• Trofeo a los tres primeros del resto de categorías (Promesa, Senior, Vet A, Vet B, Vet C).\n• Trofeo al primer lebaniego y lebaniega (empadronados en ayuntamientos de Liébana).\n• Medalla Finisher para quien complete el recorrido dentro del tiempo máximo.\n\nPremios PEÑA PRIETA TRAIL:\n• Trofeo a los tres primeros absolutos masc. y fem., y de las categorías cadete, juvenil, júnior y promesa.\n• Trofeo al primer lebaniego y lebaniega.\n\nPEÑA PRIETA MARCHA: no competitiva, sin premios.\n\nLos premios podrán ser acumulativos. Para validar una clasificación se requiere una participación mínima de 3 competidores por categoría. La entrega de trofeos será el mismo día de la prueba a las 17:00 h.', 5, false),

  (v_reg_id, 'aid_stations', 'Avituallamientos',
E'Habrá un total de 5 avituallamientos:\n\nSKY RACE:\n• KM 7 — Ledantes (pueblo): sólido + líquido.\n• KM 13,5 — Cubil de Can (choza): sólido + líquido.\n• KM 21 — Majada de Ledantes (choza): sólido + líquido.\n• KM 28,5 — Ovias (pista): sólido + líquido.\n• KM 31 — Lerelagua (pista): líquido.\n• KM 36 — Meta: sólido + líquido.\n\nTRAIL y MARCHA:\n• KM 4 — Lerelagua (pista): líquido.\n• KM 8 — Meta: sólido + líquido.\n\nLos avituallamientos en carrera se componen de fruta, frutos secos, agua y bebidas isotónicas, y deben consumirse en la zona de avituallamiento (50 m antes y después). El de meta será más completo y variado.\n\nNo habrá vasos en ningún punto: cada participante debe llevar obligatoriamente su vaso para el avituallamiento líquido. Cantimploras, bidones y mochilas de hidratación solo se rellenarán con agua natural.', 6, false),

  (v_reg_id, 'cutoff_times', 'Horarios y Tiempos de Corte',
E'Horarios de salida (3 de octubre de 2026):\n• SKY RACE: 09:00 h.\n• TRAIL: 09:30 h.\n• MARCHA: 09:30 h.\n\nTiempos de corte SKY RACE (respecto a la salida):\n• Ledantes (km 7): 2 h.\n• Cubil de Can (km 13,5): 3 h 30 min.\n• Ovias (km 28,5): 7 h.\n\nTiempo máximo: SKY RACE 8 horas; TRAIL y MARCHA 4 horas.', 7, true),

  (v_reg_id, 'mandatory_gear', 'Material Obligatorio',
E'SKY RACE:\n• Chaqueta cortavientos con capucha y manga larga de la talla del corredor/a.\n• Silbato.\n• Manta térmica o de supervivencia (mínimo 1,20 × 2,10 m).\n• Contenedor para reserva de agua (mínimo 1 litro).\n• Gorra, visera o bandana.\n• Teléfono móvil con batería cargada y los números de la organización grabados: 619 801 956 / 636 617 078.\n• Vaso o recipiente para avituallamientos líquidos.\n• Calzado y vestimenta adecuados para carreras por montaña.\n\nTRAIL y MARCHA:\n• Chaqueta cortavientos con capucha y manga larga de la talla del corredor/a.\n• Contenedor para reserva de agua (mínimo 1/2 litro).\n• Gorra, visera o bandana.\n• Teléfono móvil con batería cargada y los números de la organización grabados: 619 801 956 / 636 617 078.\n• Vaso o recipiente para avituallamientos líquidos.\n• Calzado y vestimenta adecuados para carreras por montaña.\n\nEl material obligatorio podrá ser requerido por la organización en el control de dorsales y en cualquier parte del recorrido. Todos los corredores están obligados a someterse a dicho control, bajo pena de sanción o descalificación. Según las condiciones meteorológicas, la organización podrá exigir material adicional y variar el recorrido y los tiempos de paso.', 8, true),

  (v_reg_id, 'disqualifications', 'Penalizaciones y Descalificaciones',
E'La organización podrá penalizar o descalificar a cualquier participante de las pruebas competitivas que cometa alguna de estas infracciones:\n\n• No respetar el itinerario marcado para atajar: de 15 min a descalificación.\n• Recibir ayuda o acompañamiento de personas ajenas: de 1 hora a descalificación.\n• Recibir ayuda o avituallamiento fuera de las zonas permitidas (excepto auxilio): de 15 min a descalificación.\n• No llevar puesto el dorsal o recortarlo: de 1 hora a descalificación.\n• Cambiar de dorsal o tarjeta-chip: descalificación.\n• Rehusar o cambiar las marcas del material puestas por la organización: descalificación.\n• Tirar desperdicios durante el recorrido: descalificación.\n• Abandonar o entregar los bastones fuera del lugar permitido: 1 hora de penalización.\n• Sustituir material obligatorio: de 15 min a descalificación.\n• Saltarse un control obligatorio de paso: descalificación.\n• No llevar el material requerido: de 15 min a descalificación.\n• No atender las indicaciones de la organización y árbitros: de 15 min a descalificación.\n• No pasar el control de material a requerimiento: descalificación.\n• No prestar auxilio a otros participantes: descalificación.\n\nCualquier miembro de control de la organización, sin aviso previo, está capacitado para anotar el dorsal y la infracción cometida.\n\nEl dorsal debe llevarse visible en la parte frontal del cuerpo durante toda la prueba, sin doblar ni recortar. La ayuda externa solo se permite dentro de las zonas de avituallamiento.', 9, true),

  (v_reg_id, 'responsibility', 'Aceptación y Responsabilidad',
E'• La organización declina toda responsabilidad por daños personales propios o a terceros. No obstante, se proveerá un servicio de socorro a disposición de los participantes.\n• El corredor será responsable de su seguridad si decide entregar el dorsal en un puesto de control o avituallamiento y alcanzar la línea de meta por sus propios medios.\n• Para todo lo no especificado en este reglamento, los corredores se acogerán a lo dispuesto por el Comité Organizador, apoyado en el Reglamento de Trail FEDME.\n• La inscripción supone la conformidad con los artículos del presente reglamento. La participación en la SKY RACE, TRAIL o MARCHA comporta su aceptación sin reservas.', 10, true),

  (v_reg_id, 'data_protection', 'Protección de Datos y Derechos de Imagen',
E'Todos los participantes, por el hecho de serlo, aceptan el presente reglamento y dan su consentimiento para que el Ayuntamiento de Vega de Liébana, de forma directa o mediante terceras entidades, trate informáticamente y con finalidad exclusivamente deportiva, promocional o comercial sus datos de carácter personal, así como su imagen dentro de la prueba mediante fotografías, vídeos, etc.\n\nConforme a la normativa de protección de datos de carácter personal, el participante podrá ejercer su derecho de acceso a estos ficheros con el objeto de rectificar o cancelar de forma parcial o total su contenido, solicitándolo por correo electrónico a liebana@ayto-vegadeliebana.', 11, true);

  RAISE NOTICE 'Reglamento creado con 11 secciones (sin publicar — revísalo y publícalo desde el admin).';
END $$;
